### ISSUE TITLE
WrappedConfig Strings don't seem to read from files

### ISSUE THREAD

**Issue by sisby-folk** [QuiltMC/quilt-config#28]
(from [kaleido#2](https://github.com/sisby-folk/kaleido-config/issues/2))

under a quick test, all the basic object types seem to work except String.

![image](https://github.com/QuiltMC/quilt-config/assets/55819817/27c95806-f2b6-418d-b2ea-a04e26bf1ac8)

![image](https://github.com/QuiltMC/quilt-config/assets/55819817/629df644-c8ae-499c-8e5a-7e28097abf42)

![image](https://github.com/QuiltMC/quilt-config/assets/55819817/741f1e03-cc0b-4faf-b0c3-9c25df8d594d)

**Comment by OroArmor** [comment]
I believe this is a problem with the old `WrappedConfig` system, as JVM details can change whether or not to modify a final field. If you switch to the new `ReflectiveConfig` system, that should work.

**Comment by sisby-folk** [comment]
We're die-hard wrappedconfig users and strongly feel it's one of the main advantage qconfig has over other libraries - if strings don't work in wrapped, we'd love a workaround for just that type specifically.

**Comment by ix0rai** [comment]
@sisby-folk it seems like the only reason other types currently work is because the JVM isn't perfect and doesn't do constant inlining consistently, as discussed in [discord](https://discord.com/channels/817576132726620200/1103988178945323009/1206808293037838416). if we were to implement a workaround for strings, it would be perfectly possible that a Java update would break other types. as such, I don't really see how we can support wrapped configs long-term.

**Comment by sisby-folk** [comment]
Having read the thread, doesn't removing the requirement for the field to be final solve this problem? 

It's correct that setting primitives in code wouldn't work - but they never have, and that just needs to be documented if it can't practically be enforced by the compiler.

**Comment by ix0rai** [comment]
removing the final requirement does make everything work -- but the design becomes inconsistent, stuff will silently fail, and I'm not sure docs are enough mitigation for the newly weird behaviour

to me, dropping the final requirement on just a few select types is even worse, since it introduces yet another inconsistency

**Comment by lukebemish** [comment]
Requiring the field to be non-final fixes the problem, yes, but at that point you've removed the main advantage of wrapped-config - the idea of an immutable state read in.

If you were to go with this sort of WrappedConfig system, you'd want to force *nothing* to be final - while it might work "right now" for lists/maps, there's no reason a sufficiently smart JVM couldn't find places to safely inline those or do other weirdnesses that this wouldn't work with

**Comment by sisby-folk** [comment]
As someone who uses wrappedconfig in like eight mods, it doesn't remove the main advantage of wrappedconfig for us - we like direct field access. a public static field of a standard java type (list, map, boolean, etc) is an intuitive thing for a config value to be, and I like how it looks when read out.

nothing being allowed to be final seems fine but can we make sure that's a compile time warning or error and not a runtime crash? We need to preserve stability on our end.

**Comment by ix0rai** [comment]
making that change requires breaking the wrapped config API, which is a no-go on our end due to QLoader.

what I could see as a future for wrapped is you pulling it into kaleido, and supporting it from there!

**Comment by lukebemish** [comment]
Unfortunately that's not something that can easily be done as a compile-time warning or anything either, at least not without a custom annotation processor or something

**Comment by sisby-folk** [comment]
I don't see the issue, can't the requirement for fields to be final just be dropped and a warning logged at runtime when a field _is_ final?

wrappedconfigs should at least be fixed before they're deleted.

**Comment by ix0rai** [comment]
yeah, we can do that
I'll look into that change sometime this week

**Comment by sisby-folk** [comment]
If the warning needs to be dev only to avoid players complaining that's fine, I just wanna have this last use case working before any big migration or rework (one of the kaleido things we wanted to ensure is not breaking api without changing classpath!)

**Comment by ix0rai** [comment]
the warning would be global (probably just via sysout lol) because I am too lazy to special-case stuff in QLoader :p

**Comment by sisby-folk** [comment]
This is looking really good! one issue - this warning shouldn't be applying to maps or lists should it?
![image](https://github.com/QuiltMC/quilt-config/assets/55819817/2af2a84f-8e3d-424f-90dc-aa8e5e9e7949)

**Comment by lukebemish** [comment]
To what degree the JVM JIT trims out references to final fields is an implementation detail, so I'd argue it definitely should apply to all final fields being replaced this way

**Comment by ix0rai** [comment]
it's applying to everything for that reason, and simply for consistency

**Comment by sisby-folk** [comment]
sure thing, fair enough - I'll just go with non-final for everything then!
