### ISSUE TITLE
Add display name and naming scheme metadata

### ISSUE THREAD

**Issue by anonymous123-code** [QuiltMC/quilt-config#30]
Since another intention of quilt config is to allow for mods to automatically generate config screens / menus, configs may also need display name metadata.

In order to allow for this, I suggest a `@DisplayName` and `@DisplayNameConvention` as well as the corresponding metadata, akin to `@SerializedName` and `@SerializedNameConvention` as described in #29 .

In order to allow for translatables, I suggest a `translatable` parameter which is by default false. The value would need to be handled by the specific implementation, in order to be independent from Minecraft.

**Comment by ix0rai** [comment]
can you elaborate on display name convention? if it would work similarly to a serialised name convention annotation (automatically converting field names to a readable string), I'm not a fan as it wouldn't support translatable text

**Comment by ix0rai** [comment]
I still don't really like that

also, for translations -- I don't think there's any need for a parameter. we can simply have our mod attempt to translate everything, and it'll just naturally ignore names that aren't valid translation keys
