### ISSUE TITLE
Add metadata to indicate a warning should be displayed before a change is applied

### ISSUE THREAD

**Issue by anonymous123-code** [QuiltMC/quilt-config#31]
A common concern with automatic config menus is that users might expect values to be applied directly after saving. This metadata should allow to automatically display warnings if a changed option is saved. In order to help users, some common cases are already defined as an enum. 

Note that if no screen-only related metadata is present for a mod, it might be safer to assume that the config requires a restart to apply. I'm not sure if this should be done on quilt-configs side

Applicable to config, section, and option.

Parameters:
- `value`: ChangeWarning enum
- `custom`: String default empty

`ChangeWarning` options:
- `RequiresRestart` requires the application to restart to apply
- `Unsafe` stuff may/will go wrong, and it's intentional
- `Experimental` not mature enough, may go wrong
- `CustomTranslatable` see custom for translatable string
- `Custom` use custom

**Comment by ix0rai** [comment]
love love love this idea

**Comment by ix0rai** [comment]
> Note that if no screen-only related metadata is present for a mod, it might be safer to assume that the config requires a restart to apply. I'm not sure if this should be done on quilt-configs side

this should be done on the side of the config screen generator, and should be easy with the new API method I added for getting all metadata

**Comment by OroArmor** [comment]
> love love love this idea

I also love love love this idea.
